### ISSUE TITLE
Image path

### ISSUE THREAD

**Issue by jlin-vt** [zwbetz-gh/vanilla-bootstrap-hugo-theme#11]
I put images under `static/icon/my_image.png)`.  I do

```
![Example image](/icon/my_image.png)
```

I can see it on local, but when I deploy it on github. it won't show.

**Comment by zwbetz-gh** [comment]
This is not a theme-specific issue. You'll have better luck asking your question on the hugo support forum: https://discourse.gohugo.io/. Closing this.
