### ISSUE TITLE
Problems with audio in posts

### ISSUE THREAD

**Issue by victorsnk** [zwbetz-gh/vanilla-bootstrap-hugo-theme#13]
Good afternoon. I insert audio in the posts and they do not appear. For a while everything was correct but suddenly it's gone. Could you tell me what the problem is?

Thank you.

This is example pages: https://victorsnk.gitlab.io/habando_tecnologia_2019/ you can see it in my gitlab

**Comment by zwbetz-gh** [comment]
This sounds like a general issue, not a theme specific issue. Try asking your question at the support forums https://discourse.gohugo.io/
