### ISSUE TITLE
How to change the size of title?

### ISSUE THREAD

**Issue by jlin-vt** [zwbetz-gh/vanilla-bootstrap-hugo-theme#16]
Hi. Any way to customize the font size of the title(and header) in markdown?
Thanks!

**Comment by zwbetz-gh** [comment]
I'm assuming you mean the `<h1>` element, aka the first heading? If so, then you can add CSS to target it. For example

```css
h1 {
  color: red;
}
```

**Comment by jlin-vt** [comment]
thanks!
