### ISSUE TITLE
Vanilla theme is not supporting blockquoate

### ISSUE THREAD

**Issue by PuneethaPai** [zwbetz-gh/vanilla-bootstrap-hugo-theme#19]
**Describtion**
The generated html even though has <blockquoate></blockquoate> it doesn't work.
Pls refer here: https://themes.gohugo.io//theme/vanilla-bootstrap-hugo-theme/markdown-syntax/

<img width="736" alt="Screenshot 2020-04-08 at 10 19 49 PM" src="https://user-images.githubusercontent.com/21996583/78811357-6230e800-79e7-11ea-97d8-cd622b43db94.png">

**Comment by zwbetz-gh** [comment]
This is on purpose. It is how the theme styles blockquotes. Feel free to override the CSS to make it look how you want. 

References:
- boostrap blockquote shortcode usage https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme#bootstrap-blockquote
- live demo of above https://vanilla-bootstrap-hugo-theme.netlify.com/quotes-by-carl-jung/

**Comment by PuneethaPai** [comment]
Thank You. Sorry for this.
