### ISSUE TITLE
Relative URls all the way to subpages

### ISSUE THREAD

**Issue by daviddias** [zwbetz-gh/vanilla-bootstrap-hugo-theme#2]
**Describe the bug**

Hi there! I'm really liking your simple theme and I want to upgrade my page to use it, so thank you in the first place for creating it :)

I'm having trouble at getting relativeURLs to work correctly and I believe that it can be considered a bug. I know that other themes handle it fairly well and it has been one of the main reasons why I recommend Hugo to people, because it can automatically handle pages being loaded at a domain root (e.g. normal website.com) or a path (using [IPFS ipfs.io/ipfs/webPageHash](https://ipfs.io/))

**To Reproduce**

You can get the code at https://github.com/daviddias/daviddias.me/tree/go-vanilla and run `./publish.sh` yourself or you can visit https://ipfs.io/ipfs/QmVMKKSioSmR1EhrTw1ZLcoFmPLpng6eWFYpUZhpJAthJx/blog/ to see how the page gets wonky.

It seems that https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme/blob/master/layouts/partials/script.html#L1 never gets "relative'zed" 

**Expected behavior**

The Webpage to load regularly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Firefox Quantum
 - Version 64

**Comment by zwbetz-gh** [comment]
Hi @daviddias -- you're likely seeing this behavior because your [`baseURL` is empty](https://github.com/daviddias/daviddias.me/blob/30a79409e7dd7c464315ea2c6673af986824c6d8/config.yaml#L1). It needs to be the URL of you site.

**Comment by daviddias** [comment]
@zwbetz-gh I understand your answer, however, I think it only applies if I were only to load this webpage from somedomain.com. My use case is that I want to be able to load it from:

- somedomain.com
- someIPFSGateway.com/ipfs/ContentAddressOfTheWebsite

And I can't know before hand which is which. This way, each subpage needs to have its urls relative to the root of the page but without using absolute paths or relying on a specific domain. 

Let me know if my explanation makes sense :)

**Comment by zwbetz-gh** [comment]
FYI, Hugo sites should have a valid `baseURL` value. In your specific case (which is an outlier), I see two options: 

(1) Have two separate builds for your site, then pass in the `baseURL` through CLI for each one. For example:
```
hugo --baseURL https://example.org/
```

(2) Override the `head.html` partial to meet your specific needs. For example, copy:
```
themes/vanilla-bootstrap-hugo-theme/layouts/partials/head.html
```

To:
```
layouts/partials/head.html
```

Then edit this line:
```
<link rel="stylesheet" href="{{ "css/bootstrap.min.css" | absURL }}">
```

**Comment by zwbetz-gh** [comment]
In the above, you could try replacing `absURL` with `relURL`

**Comment by daviddias** [comment]
I'm not having a lot of luck but perhaps I'm missing something. I checked the docs -- https://gohugo.io/functions/relurl/ -- and the suggestion does indeed make sense. Let me experiment more to see if I find where it breaks.

**Comment by daviddias** [comment]
Update: nvm! I was updating it incorrectly, it totally works! Thank you! I own you a cup of coffee or tea :)

PS: would you consider switching to relURL by default on your theme?

**Comment by zwbetz-gh** [comment]
Per the [hugoThemes README](https://github.com/gohugoio/hugoThemes/blob/master/README.md#common-permalink-issues), I have to use `absURL` so that my theme demo works correctly. 

Glad you got it working. Here's another option for you:

(3) Fork this theme, then make the `relURL` change. This would keep you from having to override theme head partial.

**Comment by zwbetz-gh** [comment]
Thinking about this some more. If both those URLs "resolve" to the same place, then try using one of them for the baseURL. Report back after your testing.

**Comment by zwbetz-gh** [comment]
Judging by your now functional site, looks like you've got things working :)
Closing this issue.

**Comment by daviddias** [comment]
Thank you for all the help @zwbetz-gh! I still haven't decided in which option to go (fork vs overwrite) but I know enough to get things going now.

One thing on:

> Per the hugoThemes README, I have to use absURL so that my theme demo works correctly.

I believe that isn't 100% accurate. If you add https://github.com/daviddias/daviddias.me/blob/master/config.yaml#L2 and then use relURL, you should be good to go for the demo webpage as well.

**Comment by zwbetz-gh** [comment]
See [Hugo Issue 5488](https://github.com/gohugoio/hugo/issues/5488) for details
