### ISSUE TITLE
How can i turn to the next page in the blog article index?

### ISSUE THREAD

**Issue by jacklanda** [zwbetz-gh/vanilla-bootstrap-hugo-theme#20]
How can i turn to the next page in my blog article index, 
although I do not know frontend at all.
When i use Vanilla,  I found that i can not set the buttons like "next page" & "pre page" on the page of article index.
Is there any Built-in options in Vanilla? Thank u.

the buttons i imagine like this:
![2020-08-13_13-41](https://user-images.githubusercontent.com/54089835/90098531-0b5b6680-dd6b-11ea-9696-887c8f08e320.png)

**Comment by zwbetz-gh** [comment]
Hi there, I have no plans to add this. 

If you want to add it to your fork or custom copy, you'll need to read the [pagination](https://gohugo.io/templates/pagination/#readout) docs and then edit the [list template](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme/blob/master/layouts/_default/list.html)
