### ISSUE TITLE
github site rendered incorrectly

### ISSUE THREAD

**Issue by jlin-vt** [zwbetz-gh/vanilla-bootstrap-hugo-theme#6]
**Describe the bug**
github site rendered incorrectly. (it was perfect on http://localhost:1313)

This is the output on github page
![Screen Shot 2019-08-17 at 11 08 50 PM](https://user-images.githubusercontent.com/19511714/63220891-5dac7c00-c145-11e9-8ca4-0e9d68067f43.png)

**To Reproduce**
1. git clone repo under `./themes`
2. `hugo server --theme=vanilla --buildDrafts --watch`
3. `hugo --theme=<themename> --buildDrafts --baseUrl="http://<username>.github.io"` 
4.  push to the github master

**Screenshots**
see attached

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - MAC version: `mac high sierra 10.13.6 (17G65)`
 - Hugo: `Hugo Static Site Generator v0.57.2/extended darwin/amd64`

thanks!

**Comment by jlin-vt** [comment]
supposed to be 
![Screen Shot 2019-08-17 at 11 19 13 PM](https://user-images.githubusercontent.com/19511714/63220909-89c7fd00-c145-11e9-9a24-fb9cfe9ce9a9.png)

**Comment by zwbetz-gh** [comment]
Hello there - this is likely an issue with your configuration, not with the theme. But I'll try to help. 

First, change your baseURL to use `https`

**Comment by jlin-vt** [comment]
Hi thanks for your speedy reply. The homepage is fixed, but the other tabs are still rendered incorrectly.
![Screen Shot 2019-08-18 at 11 56 04 AM](https://user-images.githubusercontent.com/19511714/63228928-5457f980-c1af-11e9-9285-a449239cac81.png)
![Screen Shot 2019-08-18 at 11 55 57 AM](https://user-images.githubusercontent.com/19511714/63228929-5457f980-c1af-11e9-852c-e7d240d0c597.png)

**Comment by zwbetz-gh** [comment]
Try doing a clean redeploy of your site

**Comment by jlin-vt** [comment]
Here is what I do:
1. `hugo new site <mysite>'
2. `git clone` `vanilla-bootstrap-hugo-theme` under `./themes`
3.  copy staff of `exampleSite` to the root
4. `hugo -t vanilla-bootstrap-hugo-theme` works fine
5.  `hugo --theme=vanilla-bootstrap-hugo-theme --buildDrafts --baseUrl="https://<username>.github.io"` (I try `hugo --theme=vanilla-bootstrap-hugo-theme` also)
6. cd `./public`
7. git push

got same result

**Comment by zwbetz-gh** [comment]
I said _clean_ for a reason :)

So clean out your `public` dir with a `rm -r public/*`

Also, add this flag to your build command `--cleanDestinationDir`

**Comment by jlin-vt** [comment]
does it mean I have to clean my `public` every time I do `git push`?

**Comment by zwbetz-gh** [comment]
I would clean it before you do a `git add`
