### ISSUE TITLE
How to customized CSS?

### ISSUE THREAD

**Issue by CicoZhang** [zwbetz-gh/vanilla-bootstrap-hugo-theme#8]
```
  {{ range .Site.Params.customCSS }}
  <link rel="stylesheet" href="{{ "/css/" | relURL }}{{ . }}">
  {{ end }}
```
has been added to head.html; it should work. However, if I overwrite `.btn` in custom.css,

```
.btn {
    display: inline-block;
    font-weight: 400;
    color: #212529;
    text-align: center;
    vertical-align: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-color: transparent;
    border: 1px dashed transparent;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    border-radius: .25rem;
    transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
```
The only change is from "solid" to "dashed" in "border", it does not show the correct style. 
![image](https://user-images.githubusercontent.com/11710225/66168002-3c8fe400-e63c-11e9-8bc5-2908f1662cff.png)
I had expected it to be:
![image](https://user-images.githubusercontent.com/11710225/66168034-57625880-e63c-11e9-87ff-b09a8a43d180.png)

So my question is, what is the proper way of customizing CSS? Thanks in advance.

**Comment by zwbetz-gh** [comment]
The fact that you were able to change the appearance of the button tells me that your custom CSS config if valid. I suspect the issue is in your CSS itself. 

Another option is to _override_ the theme's CSS file. You can do this by copying:
```
themes/vanilla-bootstrap-hugo-theme/static/css/bootstrap.min.css
``` 
To: 
```
static/css/bootstrap.min.css
```
Then making your changes there.

**Comment by zwbetz-gh** [comment]
You can also override the inline CSS by copying file:
```
themes/vanilla-bootstrap-hugo-theme/layouts/partials/style.html
``` 
To: 
```
layouts/partials/style.html
```
Then making your changes there.
