### ISSUE TITLE
How to set the width of the picture via bootstrap-card?

### ISSUE THREAD

**Issue by CicoZhang** [zwbetz-gh/vanilla-bootstrap-hugo-theme#9]
After setting Resize, the picture is indeed resized, but the display with is not changed. How can change the display width?

**Comment by zwbetz-gh** [comment]
Fixed in https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme/commit/276594607a8fb3836fbe7638dcc1f9d53c19f856
